name: Publish Website to CPanel
on:
  push:
    branches:
      - staging
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./wp-content/themes/flatsome-child
    steps:
     -  uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
     -  name: FPT-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./wp-content/themes/flatsome-child
